import './globals.css'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { Providers } from '@/components/Providers'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex min-h-screen flex-col' suppressHydrationWarning={true}>
        <Providers>
        <Header />
        <main className='flex flex-1 max-w-7xl mx-auto flex-col'>
        {children}
        </main>
        <Footer />
        </Providers>
      </body>
    </html>
  )
}
